nixPacks:
  phases:
    setup:
      nixPkgs:
        - nodejs_20
        - openjdk17
    install:
      cmds:
        - npm ci
    build:
      cmds:
        - echo "No build step required"
  start:
    cmd: node src/index.js
