[phases.setup]
nixPkgs = ["nodejs_20", "openjdk17", "python3", "gcc", "gnumake", "libopus"]

[phases.install]
cmds = ["npm install --production --no-optional"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "node src/index.js"
